version: '3.9'

services:
    # front_end:
    #     image: vuepong
    #     container_name: MyPong
    #     init: true
    #     restart: on-failure
    
    postgres:
        image: postgres:alpine
        ports:
            - 5432:5432
        env_file:
            - ./envs/postgres.env
        volumes:
            - postgres_persistence:/var/lib/postgresql/data
    back:
        build:
            context: ./srcs/back
            target: dev
        env_file:
            - ./envs/postgres.env
            - ./envs/back.env
        volumes:
        # for hot-reloading using Nodemon
            - ./srcs/back/src:/app/src
        depends_on:
            - postgres
        ports:
            - 3000:3000

volumes:
    postgres_persistence:
