version: '3.9'

services:
    # front_end:
    #     image: vuepong
    #     container_name: MyPong
    #     init: true
    #     restart: on-failure
    #     network:
    #       - frontend
    
    postgres:
        image: postgres:alpine
        ports:
            - 5432:5432
        env_file:
            - ./envs/postgres.env
        restart: unless-stopped
        volumes:
            - postgres_persistence:/var/lib/postgresql/data
        networks:
            - backend
    back:
        build:
            context: ./srcs/back
            target: dev
        env_file:
            - ./envs/postgres.env
            - ./envs/back.env
        restart: unless-stopped
        volumes:
        # for hot-reloading using Nodemon
            - ./srcs/back/src:/app/src
        depends_on:
            - postgres
        ports:
            - 3000:3000
        networks:
            - backend
            - frontend


volumes:
    postgres_persistence:
        name: "postgres_persistence"
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${PWD}/postgres_persistence
    

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge